services:
  ui_scheapp:
    image: w3sherpa/scheapp-ui:latest
    ports:
      - 8091:8091
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8091
    networks:
      - scheapp_net
networks:
  scheapp_net:
    name: scheapp_net
    driver: bridge
#docker build -t scheapp-ui:latest .
#docker login -u lonheeti@gmail.com -p T3serract
#docker tag scheapp-ui w3sherpa/scheapp-ui:latest
#docker push w3sherpa/scheapp-ui:latest
